name: Publish Docker Image

on: 
  push:
    branches: [main]
    paths:
      - 'jupyter-python-example/**'
  release:
    types:
      - published
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/helloexample1

jobs:
  
   build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    
    steps:
      - name: check out
        uses: actions/checkout@v2
        
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PASSWORD }}
        
      - name: Build and Push Latest Docker Image
        id: build-and-push-latest
        uses: docker/build-push-action@v2
        with:
          context: jupyter-python-example
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
